//! POSIX shell quoting and the small amount of expansion the remote agent does
//! itself (so values never go through a shell).

use std::collections::BTreeMap;
use std::path::PathBuf;

/// Quotes `value` as a single POSIX shell word.
pub fn quote(value: &str) -> String {
    if !value.is_empty()
        && value.chars().all(|c| {
            c.is_ascii_alphanumeric()
                || matches!(c, '-' | '_' | '.' | '/' | ',' | ':' | '=' | '@' | '+')
        })
    {
        return value.to_string();
    }
    format!("'{}'", value.replace('\'', r"'\''"))
}

/// Quotes a remote path, keeping a leading `~/` expandable.
pub fn quote_path(path: &str) -> String {
    if path == "~" {
        "\"$HOME\"".to_string()
    } else if let Some(rest) = path.strip_prefix("~/") {
        format!("\"$HOME\"/{}", quote(rest))
    } else {
        quote(path)
    }
}

/// Quotes `value` as one `cmd.exe` argument. Arguments here are generated by
/// fastforge (paths, ids), so `"` and `%`, which cmd can't escape inside
/// quotes, are not expected and are dropped.
pub fn quote_cmd(value: &str) -> String {
    if !value.is_empty()
        && value.chars().all(|c| {
            c.is_ascii_alphanumeric()
                || matches!(
                    c,
                    '-' | '_' | '.' | '/' | '\\' | ':' | '=' | '@' | '+' | ',' | '~'
                )
        })
    {
        return value.to_string();
    }
    let cleaned: String = value.chars().filter(|c| !matches!(c, '"' | '%')).collect();
    format!("\"{cleaned}\"")
}

/// A Windows path for `cmd.exe`, with a leading `~` mapped to
/// `%USERPROFILE%` and `/` turned into `\`.
pub fn quote_cmd_path(path: &str) -> String {
    let (prefix, rest) = if path == "~" {
        ("%USERPROFILE%", "")
    } else if let Some(rest) = path.strip_prefix("~/").or_else(|| path.strip_prefix("~\\")) {
        ("%USERPROFILE%\\", rest)
    } else {
        ("", path)
    };
    let rest: String = rest
        .replace('/', "\\")
        .chars()
        .filter(|c| !matches!(c, '"' | '%'))
        .collect();
    format!("\"{prefix}{rest}\"")
}

/// Expands a leading `~` / `~/` against `home`.
pub fn expand_home(path: &str, home: Option<&std::path::Path>) -> PathBuf {
    match (path, home) {
        ("~", Some(home)) => home.to_path_buf(),
        (p, Some(home)) if p.starts_with("~/") => home.join(&p[2..]),
        (p, _) => PathBuf::from(p),
    }
}

/// Expands `~/`, `$VAR` and `${VAR}` in `value` using `lookup`. Unknown
/// variables expand to the empty string, like a shell.
pub fn expand_vars(value: &str, lookup: &dyn Fn(&str) -> Option<String>) -> String {
    let mut out = String::new();
    let mut rest = value;
    if let Some(tail) = rest
        .strip_prefix("~/")
        .or(if rest == "~" { Some("") } else { None })
    {
        out.push_str(&lookup("HOME").unwrap_or_default());
        if rest.len() > 1 {
            out.push('/');
        }
        rest = tail;
    }
    let chars: Vec<char> = rest.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '$' && i + 1 < chars.len() {
            if chars[i + 1] == '{'
                && let Some(end) = chars[i + 2..].iter().position(|&c| c == '}')
            {
                let name: String = chars[i + 2..i + 2 + end].iter().collect();
                out.push_str(&lookup(&name).unwrap_or_default());
                i += end + 3;
                continue;
            }
            let len = chars[i + 1..]
                .iter()
                .take_while(|c| c.is_ascii_alphanumeric() || **c == '_')
                .count();
            if len > 0 && !chars[i + 1].is_ascii_digit() {
                let name: String = chars[i + 1..i + 1 + len].iter().collect();
                out.push_str(&lookup(&name).unwrap_or_default());
                i += len + 1;
                continue;
            }
        }
        out.push(chars[i]);
        i += 1;
    }
    out
}

/// Expands every value of `templates` in order, so later entries can refer to
/// earlier ones (`PATH: ~/flutter/bin:$PATH`).
pub fn expand_env_templates(
    templates: &BTreeMap<String, String>,
    base: &dyn Fn(&str) -> Option<String>,
) -> BTreeMap<String, String> {
    let mut resolved: BTreeMap<String, String> = BTreeMap::new();
    for (key, template) in templates {
        let value = expand_vars(template, &|name| {
            resolved.get(name).cloned().or_else(|| base(name))
        });
        resolved.insert(key.clone(), value);
    }
    resolved
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quotes_words() {
        assert_eq!(quote("plain-word_1.0"), "plain-word_1.0");
        assert_eq!(quote(""), "''");
        assert_eq!(quote("a b"), "'a b'");
        assert_eq!(quote("it's"), r"'it'\''s'");
        assert_eq!(quote("$HOME"), "'$HOME'");
    }

    #[test]
    fn quotes_paths_keeping_home() {
        assert_eq!(quote_path("~"), "\"$HOME\"");
        assert_eq!(quote_path("~/a b/c"), "\"$HOME\"/'a b/c'");
        assert_eq!(quote_path("/opt/x"), "/opt/x");
    }

    #[test]
    fn quotes_for_cmd() {
        assert_eq!(quote_cmd("exec"), "exec");
        assert_eq!(quote_cmd("~/.fastforge/x-1"), "~/.fastforge/x-1");
        assert_eq!(quote_cmd("a b"), "\"a b\"");
        assert_eq!(quote_cmd("50%\""), "\"50\"");
        assert_eq!(
            quote_cmd_path("~/.fastforge/remote/ws"),
            "\"%USERPROFILE%\\.fastforge\\remote\\ws\""
        );
        assert_eq!(
            quote_cmd_path("C:/tools/fastforge.exe"),
            "\"C:\\tools\\fastforge.exe\""
        );
        assert_eq!(quote_cmd_path("~"), "\"%USERPROFILE%\"");
    }

    #[test]
    fn expands_variables() {
        let lookup = |name: &str| match name {
            "HOME" => Some("/home/me".to_string()),
            "PATH" => Some("/usr/bin".to_string()),
            _ => None,
        };
        assert_eq!(
            expand_vars("~/flutter/bin:$PATH", &lookup),
            "/home/me/flutter/bin:/usr/bin"
        );
        assert_eq!(expand_vars("${HOME}x", &lookup), "/home/mex");
        assert_eq!(expand_vars("$MISSING-$1$", &lookup), "-$1$");
        assert_eq!(expand_vars("~", &lookup), "/home/me");
        assert_eq!(expand_vars("a~b", &lookup), "a~b");
    }

    #[test]
    fn templates_see_earlier_entries() {
        let mut templates = BTreeMap::new();
        templates.insert("A_ROOT".to_string(), "~/sdk".to_string());
        templates.insert("B_BIN".to_string(), "$A_ROOT/bin".to_string());
        let base = |name: &str| (name == "HOME").then(|| "/h".to_string());
        let resolved = expand_env_templates(&templates, &base);
        assert_eq!(resolved["B_BIN"], "/h/sdk/bin");
    }
}
